# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AliasSampleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'

  # Pods for AliasSampleProject

  target 'AliasSampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AliasSampleProjectUITests' do
    # Pods for testing
  end

end
